#!/usr/bin/env python3
"""Clean up duplicates and generate final report"""
import os, re

OUT = r"D:\Skripsi_Referensi_PDF"

# Group files by index number
groups = {}
for fn in os.listdir(OUT):
    if not fn.endswith('.pdf'):
        continue
    m = re.match(r'(\d{3})_', fn)
    if not m:
        continue
    idx = m.group(1)
    fp = os.path.join(OUT, fn)
    sz = os.path.getsize(fp)
    groups.setdefault(idx, []).append((fn, sz, fp))

# Keep largest, delete smaller
deleted = 0
for idx, files in groups.items():
    if len(files) > 1:
        files.sort(key=lambda x: -x[1])  # largest first
        keep = files[0]
        for fn, sz, fp in files[1:]:
            if sz < 10000:  # corrupt/empty
                os.remove(fp)
                deleted += 1
                print(f"🗑️  Deleted {fn} (only {sz//1024}KB)")
            elif sz < keep[1] * 0.9:  # significantly smaller = different paper or lower quality
                os.remove(fp)
                deleted += 1
                print(f"🗑️  Deleted {fn} ({sz//1024}KB < {keep[1]//1024}KB of {keep[0]})")

# Count final
pdfs = [f for f in os.listdir(OUT) if f.endswith('.pdf') and os.path.getsize(os.path.join(OUT, f)) > 10000]
total_size = sum(os.path.getsize(os.path.join(OUT, f)) for f in pdfs)

print(f"\n📊 CLEANUP: {deleted} duplikat dihapus")
print(f"📊 FINAL: {len(pdfs)} PDF, {total_size//1024//1024}MB total")

# Generate clean report
with open(os.path.join(OUT, "REPORT_FINAL.md"), 'w') as f:
    f.write("# 📚 Laporan Final Download Referensi\n\n")
    f.write(f"**Skripsi:** Bioprospeksi Drynaria quercifolia sebagai Antimikroba dan Antioksidan\n")
    f.write(f"**Tanggal:** {__import__('time').strftime('%Y-%m-%d %H:%M')}\n")
    f.write(f"**Total PDF:** {len(pdfs)} file | **Total size:** {total_size//1024//1024}MB\n\n")
    
    f.write("## ✅ Berhasil Didownload ({})\n\n".format(len(pdfs)))
    for fn in sorted(pdfs):
        sz = os.path.getsize(os.path.join(OUT, fn)) // 1024
        f.write(f"- {fn} ({sz}KB)\n")
    
    f.write("\n---\n")
    f.write(f"_Auto-generated by Hermes Agent | v2→v3→v4→v5 downloader_\n")

print(f"\n📄 Final report: {OUT}\\REPORT_FINAL.md")
